function(IS_UNIQUE_DIGIT CHANNEL_VALUES)
    string(LENGTH ${CHANNEL_VALUES} LEN)
    if(LEN EQUAL 2 OR LEN EQUAL 4 OR LEN EQUAL 3 OR LEN EQUAL 7)
        set(IS_UNIQUE TRUE PARENT_SCOPE)
    else()
        set(IS_UNIQUE FALSE PARENT_SCOPE)
    endif()
endfunction()

set(TOTAL_UNIQUE "0")
file(STRINGS "input.txt" INPUT_LINES)
foreach(LINE ${INPUT_LINES})
    string(REGEX MATCH "\\| (.+$)" OUTPUT_STRING ${LINE})
    string(REPLACE " " ";" OUTPUT_VALUES ${OUTPUT_STRING})
    foreach(CHANNEL_VALUES ${OUTPUT_VALUES})
        is_unique_digit(${CHANNEL_VALUES})
        if(IS_UNIQUE)
            math(EXPR TOTAL_UNIQUE "${TOTAL_UNIQUE} + 1")
        endif()
    endforeach()
endforeach()

message(STATUS "PART 1: ${TOTAL_UNIQUE}")